
module: ARISES
author: Ryan Armiger, Becky Elkington, Xiaoyu Ma, Dan Wells
github_url: https://github.com/danwells96/ARISES

clean: true
exclude: [Packages]
theme: fullwidth
skip_undocumented: true
hide_documentation_coverage: true
min_acl: private
documentation: DocFiles/*.md
abstract: DocFiles/Sections/*.md
xcodebuild_arguments:
- -scheme
- ARISES

custom_categories:

  - name: Documentation
    children:
    - Client Design
    - Final Design
    - Design Process
    - Program Architecture
    - Testing
    - Future Work
    - Ethics Report
    - Sustainability Report
    - Meeting Minutes
    - Focus Group Report

  - name: Model
    children:
    - ModelController
    - PersistenceService
    - Insulin
    - Glucose
    - Day
    - Favourites
    - Meals
    - Exercise
    - Illness
    - Stress

  - name: Graph
    children:
    - ViewControllerGraph
    - ChartBGView
    - CustomView
    - ChartPointEllipseView

  - name: Main View
    children:
    - ViewControllerMain
    - MainViewState

  - name: Food Domain
    children:
    - ViewControllerFood
    - IndicatorControllerFood

  - name: Exercise Domain
    children:
    - ViewControllerExercise

  - name: Health Domain
    children:
    - ViewControllerHealth

  - name: Advice Domain
    children:
    - ViewControllerAdvice

  - name: Tables
    children:
    - ViewControllerTableViewCell
    - tableCellDelegate

  - name: Settings
    children:
    - SettingsBundleHelper




